In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('Train_aBjfeNk.csv')
df.head()

ID  Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0  462809    Male           No   22        No     Healthcare              1.0   
1  462643  Female          Yes   38       Yes       Engineer              NaN   
2  466315  Female          Yes   67       Yes       Engineer              1.0   
3  461735    Male          Yes   67       Yes         Lawyer              0.0   
4  462669  Female          Yes   40       Yes  Entertainment              NaN   

  Spending_Score  Family_Size  Var_1 Segmentation  
0            Low          4.0  Cat_4            D  
1        Average          3.0  Cat_4            A  
2            Low          1.0  Cat_6            B  
3           High          2.0  Cat_6            B  
4           High          6.0  Cat_6            A

In [3]:
df.shape

(8068, 11)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
ID                 8068 non-null int64
Gender             8068 non-null object
Ever_Married       7928 non-null object
Age                8068 non-null int64
Graduated          7990 non-null object
Profession         7944 non-null object
Work_Experience    7239 non-null float64
Spending_Score     8068 non-null object
Family_Size        7733 non-null float64
Var_1              7992 non-null object
Segmentation       8068 non-null object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB


In [5]:
df.describe()

ID          Age  Work_Experience  Family_Size
count    8068.000000  8068.000000      7239.000000  7733.000000
mean   463479.214551    43.466906         2.641663     2.850123
std      2595.381232    16.711696         3.406763     1.531413
min    458982.000000    18.000000         0.000000     1.000000
25%    461240.750000    30.000000         0.000000     2.000000
50%    463472.500000    40.000000         1.000000     3.000000
75%    465744.250000    53.000000         4.000000     4.000000
max    467974.000000    89.000000        14.000000     9.000000

In [6]:
df.describe(include='O')

Gender Ever_Married Graduated Profession Spending_Score  Var_1  \
count    8068         7928      7990       7944           8068   7992   
unique      2            2         2          9              3      7   
top      Male          Yes       Yes     Artist            Low  Cat_6   
freq     4417         4643      4968       2516           4878   5238   

       Segmentation  
count          8068  
unique            4  
top               D  
freq           2268

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
ID                 8068 non-null int64
Gender             8068 non-null object
Ever_Married       7928 non-null object
Age                8068 non-null int64
Graduated          7990 non-null object
Profession         7944 non-null object
Work_Experience    7239 non-null float64
Spending_Score     8068 non-null object
Family_Size        7733 non-null float64
Var_1              7992 non-null object
Segmentation       8068 non-null object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB


In [8]:
df['Profession'].value_counts()

Artist           2516
Healthcare       1332
Entertainment     949
Engineer          699
Doctor            688
Lawyer            623
Executive         599
Marketing         292
Homemaker         246
Name: Profession, dtype: int64

In [9]:
df[df['Profession'].isnull()]['Gender'].value_counts()

Male      65
Female    59
Name: Gender, dtype: int64

In [10]:
df['Work_Experience'].value_counts()

1.0     2354
0.0     2318
9.0      474
8.0      463
2.0      286
3.0      255
4.0      253
6.0      204
7.0      196
5.0      194
10.0      53
11.0      50
12.0      48
13.0      46
14.0      45
Name: Work_Experience, dtype: int64

In [11]:
df[df['Work_Experience'].isnull()]['Age'].value_counts()

33    29
37    27
28    27
31    26
25    26
      ..
77     2
82     2
72     2
71     2
75     2
Name: Age, Length: 67, dtype: int64

In [12]:
df['Family_Size'].value_counts()

2.0    2390
3.0    1497
1.0    1453
4.0    1379
5.0     612
6.0     212
7.0      96
8.0      50
9.0      44
Name: Family_Size, dtype: int64

In [13]:
df['Var_1'].value_counts()

Cat_6    5238
Cat_4    1089
Cat_3     822
Cat_2     422
Cat_7     203
Cat_1     133
Cat_5      85
Name: Var_1, dtype: int64

In [14]:
df['Ever_Married'].fillna(value='No',inplace=True)

In [15]:
df['Graduated'].fillna(value='Yes',inplace=True)

In [16]:
df['Profession'].fillna(value='Artist',inplace=True)

In [17]:
df['Work_Experience'].fillna(value=1,inplace=True)

In [18]:
df['Family_Size'].fillna(value=2,inplace=True)

In [19]:
df['Var_1'].fillna(value='Cat_6',inplace=True)

In [20]:
df.isnull().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [21]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le=LabelEncoder()

In [24]:
df['Gender']=le.fit_transform(df['Gender'])

In [25]:
df['Ever_Married']=le.fit_transform(df['Ever_Married'])

In [26]:
df['Graduated']=le.fit_transform(df['Graduated'])

In [27]:
df['Profession']=le.fit_transform(df['Profession'])

In [28]:
df['Spending_Score']=le.fit_transform(df['Spending_Score'])

In [29]:
df['Var_1']=le.fit_transform(df['Var_1'])

In [30]:
df['Segmentation']=le.fit_transform(df['Segmentation'])

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
ID                 8068 non-null int64
Gender             8068 non-null int32
Ever_Married       8068 non-null int32
Age                8068 non-null int64
Graduated          8068 non-null int32
Profession         8068 non-null int32
Work_Experience    8068 non-null float64
Spending_Score     8068 non-null int32
Family_Size        8068 non-null float64
Var_1              8068 non-null int32
Segmentation       8068 non-null int32
dtypes: float64(2), int32(7), int64(2)
memory usage: 472.9 KB


In [32]:
import xgboost as xgb

In [33]:
xgbc=xgb.XGBClassifier()

In [34]:
X=df.drop(['Segmentation','ID'],axis=1)
y=df['Segmentation']

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc=StandardScaler()

In [37]:
X_sc=pd.DataFrame(sc.fit_transform(X),columns=X.columns)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_sc, y, test_size=0.33, random_state=42)

In [40]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [41]:
pred_xgbc=xgbc.predict(X_test)

In [42]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [43]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           0       0.42      0.42      0.42       647
           1       0.39      0.35      0.36       605
           2       0.54      0.52      0.53       644
           3       0.63      0.70      0.66       767

    accuracy                           0.51      2663
   macro avg       0.49      0.50      0.50      2663
weighted avg       0.50      0.51      0.50      2663



In [44]:
print(accuracy_score(y_test,pred_xgbc))

0.5088246338715734


In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rf = RandomForestClassifier(random_state=42)

In [47]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [48]:
pred_rf=rf.predict(X_test)

In [49]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       0.42      0.39      0.40       647
           1       0.39      0.37      0.38       605
           2       0.52      0.50      0.51       644
           3       0.62      0.68      0.65       767

    accuracy                           0.50      2663
   macro avg       0.49      0.49      0.49      2663
weighted avg       0.49      0.50      0.49      2663



In [50]:
print(accuracy_score(y_test,pred_rf))

0.49831017649267745


In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
knn=KNeighborsClassifier()

In [53]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [54]:
pred_knn=knn.predict(X_test)

In [55]:
print("The accuracy of KNeighbors Classifier is ",accuracy_score(y_test,pred_knn))
print("The Confusion Matrix of KNeighbors Classifier is \n \n",confusion_matrix(y_test,pred_knn))
print("\n")
print("The Classification Report of KNeighbors Classifier is \n \n",classification_report(y_test,pred_knn))

The accuracy of KNeighbors Classifier is  0.4731505820503192
The Confusion Matrix of KNeighbors Classifier is 
 
 [[298 149  81 119]
 [205 197 142  61]
 [128 150 300  66]
 [167  82  53 465]]


The Classification Report of KNeighbors Classifier is 
 
               precision    recall  f1-score   support

           0       0.37      0.46      0.41       647
           1       0.34      0.33      0.33       605
           2       0.52      0.47      0.49       644
           3       0.65      0.61      0.63       767

    accuracy                           0.47      2663
   macro avg       0.47      0.46      0.47      2663
weighted avg       0.48      0.47      0.48      2663



In [56]:
from sklearn.linear_model import LogisticRegressionCV

In [57]:
lr=LogisticRegressionCV(cv=5,max_iter=10000)

In [58]:
lr.fit(X_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=5, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=10000, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [59]:
pred_lr=lr.predict(X_test)

In [60]:
print(lr.score(X_train,y_train))
print(lr.score(X_test,y_test))

0.4956521739130435
0.4949305294780323


In [61]:
print("The accuracy of Logistic Regression is ",accuracy_score(y_test,pred_lr))
print("The Confusion Matrix of Logistic Regression is \n \n",confusion_matrix(y_test,pred_lr))
print("\n")
print("The Classification Report of Logistic Regression is \n \n",classification_report(y_test,pred_lr))

The accuracy of Logistic Regression is  0.4949305294780323
The Confusion Matrix of Logistic Regression is 
 
 [[278  41 143 185]
 [195  63 261  86]
 [ 99  52 396  97]
 [121  17  48 581]]


The Classification Report of Logistic Regression is 
 
               precision    recall  f1-score   support

           0       0.40      0.43      0.41       647
           1       0.36      0.10      0.16       605
           2       0.47      0.61      0.53       644
           3       0.61      0.76      0.68       767

    accuracy                           0.49      2663
   macro avg       0.46      0.48      0.45      2663
weighted avg       0.47      0.49      0.46      2663



In [68]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import ExtraTreeClassifier

In [69]:
extra_tree = ExtraTreeClassifier(random_state=42)

In [70]:
bgc=BaggingClassifier(extra_tree)

In [71]:
bgc.fit(X_train,y_train)

BaggingClassifier(base_estimator=ExtraTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features='auto',
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     random_state=42,
                                                     splitter='random'),
                  bootstrap=True, bootstr

In [72]:
pred_bgc=bgc.predict(X_test)

In [73]:
print("The accuracy of Bagging is ",accuracy_score(y_test,pred_bgc))
print("The Confusion Matrix of Bagging is \n \n",confusion_matrix(y_test,pred_bgc))
print("\n")
print("The Classification Report of Bagging is \n \n",classification_report(y_test,pred_bgc))

The accuracy of Bagging is  0.48253849042433344
The Confusion Matrix of Bagging is 
 
 [[265 139  92 151]
 [166 211 157  71]
 [ 98 176 301  69]
 [139  66  54 508]]


The Classification Report of Bagging is 
 
               precision    recall  f1-score   support

           0       0.40      0.41      0.40       647
           1       0.36      0.35      0.35       605
           2       0.50      0.47      0.48       644
           3       0.64      0.66      0.65       767

    accuracy                           0.48      2663
   macro avg       0.47      0.47      0.47      2663
weighted avg       0.48      0.48      0.48      2663



In [74]:
from sklearn.ensemble import VotingClassifier

In [75]:
ensemble=[('Random Forest',rf),('Knn',knn),('Logistic Regression',lr),('XGBClassifier',xgbc),('Bagging',bgc)]

In [76]:
vc=VotingClassifier(estimators=ensemble)

In [77]:
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('Random Forest',
                              RandomForestClassifier(bootstrap=True,
                                                     ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features='auto',
                                                     max_leaf_nodes=None,
                                                     max_samples=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.

In [78]:
pred_vc=vc.predict(X_test)

In [79]:
print("The accuracy of Voting Classifier is ",accuracy_score(y_test,pred_vc))
print("The Confusion Matrix of Voting Classifier is \n \n",confusion_matrix(y_test,pred_vc))
print("\n")
print("The Classification Report of Voting Classifier is \n \n",classification_report(y_test,pred_vc))

The accuracy of Voting Classifier is  0.509200150206534
The Confusion Matrix of Voting Classifier is 
 
 [[306 117  73 151]
 [203 179 159  64]
 [110 127 327  80]
 [129  55  39 544]]


The Classification Report of Voting Classifier is 
 
               precision    recall  f1-score   support

           0       0.41      0.47      0.44       647
           1       0.37      0.30      0.33       605
           2       0.55      0.51      0.53       644
           3       0.65      0.71      0.68       767

    accuracy                           0.51      2663
   macro avg       0.49      0.50      0.49      2663
weighted avg       0.50      0.51      0.50      2663

